//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Rent_A_Field
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnik()
        {
            this.Povratna_informacija_obrazac = new HashSet<Povratna_informacija_obrazac>();
            this.Prihvati_prigovor = new HashSet<Prihvati_prigovor>();
            this.Rezervacija_opreme = new HashSet<Rezervacija_opreme>();
            this.Rezervacija_prostora = new HashSet<Rezervacija_prostora>();
            this.Rezervacija_trenera = new HashSet<Rezervacija_trenera>();
            this.Trening_program = new HashSet<Trening_program>();
        }
    
        public int korisnik_id { get; set; }
        public string ime_prezime { get; set; }
        public string email { get; set; }
        public string broj_mobitela { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public Nullable<int> uloga_id { get; set; }
    
        public virtual Uloga Uloga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Povratna_informacija_obrazac> Povratna_informacija_obrazac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prihvati_prigovor> Prihvati_prigovor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija_opreme> Rezervacija_opreme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija_prostora> Rezervacija_prostora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija_trenera> Rezervacija_trenera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trening_program> Trening_program { get; set; }
    }
}
