//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Rent_A_Field
{
    using System;
    using System.Collections.Generic;
    
    public partial class Povratna_informacija_obrazac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Povratna_informacija_obrazac()
        {
            this.Prihvati_prigovor = new HashSet<Prihvati_prigovor>();
        }
    
        public int pi_obrazac_id { get; set; }
        public string tekst { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<int> korisnik_id { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prihvati_prigovor> Prihvati_prigovor { get; set; }
    }
}
