//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Rent_A_Field
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prihvati_prigovor
    {
        public int prihvati_prigovor_id { get; set; }
        public Nullable<int> korisnik_id { get; set; }
        public Nullable<int> pi_obrazac_id { get; set; }
        public Nullable<int> prihvaceno { get; set; }
        public string komentar { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Povratna_informacija_obrazac Povratna_informacija_obrazac { get; set; }
    }
}
