//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Rent_A_Field
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija_prostora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervacija_prostora()
        {
            this.Rezultats = new HashSet<Rezultat>();
        }
    
        public int rezervacija_prostora_id { get; set; }
        public Nullable<int> sportski_prostor_id { get; set; }
        public Nullable<int> korisnik_id { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string vrijeme_od { get; set; }
        public Nullable<int> duljina_rezervacije { get; set; }
        public Nullable<int> placeno { get; set; }
        public Nullable<double> cijena { get; set; }
        public Nullable<int> dogadaj_id { get; set; }
    
        public virtual Dogadaj Dogadaj { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Sportski_prostor Sportski_prostor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezultat> Rezultats { get; set; }
    }
}
