//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Rent_A_Field
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezultat
    {
        public int rezultat_id { get; set; }
        public string sport { get; set; }
        public string rezultat1 { get; set; }
        public int rezervacija_prostora_id { get; set; }
    
        public virtual Rezervacija_prostora Rezervacija_prostora { get; set; }
    }
}
